# Site settings
title: Your Legal Finance Site
email: your-email@example.com
description: Comprehensive legal and financial guidance
baseurl: "" # Leave empty for root domain
url: "https://yourdomain.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Multi-language support
languages: ["en", "hi"]
default_lang: "en"

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Sass
sass:
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
