
# Pagination settings
paginate: 8
paginate_path: "/page:num/"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
description: "Right to Respect - Combating harassment and protecting rights in India"
author: "Right to Respect Team"

# Excerpt settings
excerpt_separator: <!--more-->

# Show future posts (if you have scheduled posts)
future: true

# Build settings
markdown: kramdown
highlighter: rouge

# Social media (optional - add your actual handles)
twitter:
  username: your_twitter_handle
social:
  name: Right to Respect
  links:
    - https://twitter.com/your_handle
    - https://facebook.com/your_page

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
