# Site settings
title: Right to Respect
description: Combating harassment and protecting rights in India
baseurl: ""
url: "https://righttorespect.in"

# Pagination settings - REMOVE LIMITS
paginate: 999  # Shows 999 posts per page (unlimited)
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: rouge
