# Site settings
title: Right to Respect
description: Combating harassment and protecting rights in India
baseurl: ""
url: "https://righttorespect.in"

# Pagination settings - REMOVE LIMITS
paginate: 999  # Shows 999 posts per page (unlimited)
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: rouge
# Pagination settings
paginate: 8  # Show 8 posts per page
paginate_path: "/page:num/"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Excerpt settings
excerpt_separator: <!--more-->

# Show future posts (if you have scheduled posts)
future: true

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
