# Site settings
title: Right to Respect
email: your-email@example.com
description: >-
  Website exposing loan recovery agency harassment and providing 
  resources for victims. Know your rights and protect yourself 
  from illegal debt collection practices.

baseurl: ""
url: "https://righttorespect.in"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalink structure
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Social media
twitter_username: your_twitter_handle
github_username: harassmentshieldindia
