title: Right to Respect
email: contact@righttorespect.in
description: >-
  Combating harassment and protecting rights in India
baseurl: "/righttorespect-blog"
url: "https://harassmentshieldindia.github.io"
theme: minima

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
